"""empty message

Revision ID: 292cf7b6f13e
Revises: 3c11c7cfbd81
Create Date: 2015-03-22 10:31:45.494821

"""

# revision identifiers, used by Alembic.
revision = '292cf7b6f13e'
down_revision = '3c11c7cfbd81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_statistics',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('solutions_count', sa.Integer(), server_default=u'0', nullable=False),
    sa.Column('accepts_count', sa.Integer(), server_default=u'0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_statistics_accepts_count'), 'problem_statistics', ['accepts_count'], unique=False)
    op.create_index(op.f('ix_problem_statistics_solutions_count'), 'problem_statistics', ['solutions_count'], unique=False)
    op.create_table('contest_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'news', sa.Column('is_display', sa.Boolean(), server_default=sa.text(u'true'), nullable=False))
    op.drop_column(u'news', 'display')
    op.add_column(u'problem', sa.Column('author', sa.String(length=128), nullable=True))
    op.add_column(u'problem', sa.Column('date_modified', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column(u'problem', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('hint', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('input', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('is_display', sa.Boolean(), server_default=sa.text(u'true'), nullable=True))
    op.add_column(u'problem', sa.Column('memory_limit', sa.Integer(), nullable=True))
    op.add_column(u'problem', sa.Column('output', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('sample_code', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('sample_input', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('sample_output', sa.UnicodeText(), nullable=True))
    op.add_column(u'problem', sa.Column('source', sa.String(length=512), nullable=True))
    op.add_column(u'problem', sa.Column('time_limit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'problem', 'time_limit')
    op.drop_column(u'problem', 'source')
    op.drop_column(u'problem', 'sample_output')
    op.drop_column(u'problem', 'sample_input')
    op.drop_column(u'problem', 'sample_code')
    op.drop_column(u'problem', 'output')
    op.drop_column(u'problem', 'memory_limit')
    op.drop_column(u'problem', 'is_display')
    op.drop_column(u'problem', 'input')
    op.drop_column(u'problem', 'hint')
    op.drop_column(u'problem', 'description')
    op.drop_column(u'problem', 'date_modified')
    op.drop_column(u'problem', 'author')
    op.add_column(u'news', sa.Column('display', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column(u'news', 'is_display')
    op.drop_table('contest_user')
    op.drop_index(op.f('ix_problem_statistics_solutions_count'), table_name='problem_statistics')
    op.drop_index(op.f('ix_problem_statistics_accepts_count'), table_name='problem_statistics')
    op.drop_table('problem_statistics')
    ### end Alembic commands ###
