"""update contest model

Revision ID: 299d5e302ccd
Revises: 1f8b42b9327d
Create Date: 2015-05-25 16:26:11.783241

"""

# revision identifiers, used by Alembic.
revision = '299d5e302ccd'
down_revision = '1f8b42b9327d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    op.drop_column('contest', 'is_hiden')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('is_hiden', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=True))
    op.drop_column('contest', 'is_hidden')
    ### end Alembic commands ###
