"""empty message

Revision ID: 2c6077bbbaa7
Revises: 366d5d12bb83
Create Date: 2015-04-11 14:44:07.290702

"""

# revision identifiers, used by Alembic.
revision = '2c6077bbbaa7'
down_revision = '366d5d12bb83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_code_date_created'), 'code', ['date_created'], unique=False)
    op.create_index(op.f('ix_code_solution_id'), 'code', ['solution_id'], unique=False)
    op.create_index(op.f('ix_compile_info_code_id'), 'compile_info', ['code_id'], unique=False)
    op.create_index(op.f('ix_compile_info_date_created'), 'compile_info', ['date_created'], unique=False)
    op.create_index(op.f('ix_contest_date_created'), 'contest', ['date_created'], unique=False)
    op.create_index(op.f('ix_contest_user_id'), 'contest', ['user_id'], unique=False)
    op.create_index(op.f('ix_contest_problem_contest_id'), 'contest_problem', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_problem_date_created'), 'contest_problem', ['date_created'], unique=False)
    op.create_index(op.f('ix_contest_problem_ordinal'), 'contest_problem', ['ordinal'], unique=False)
    op.create_index(op.f('ix_contest_problem_problem_id'), 'contest_problem', ['problem_id'], unique=False)
    op.create_index(op.f('ix_contest_user_contest_id'), 'contest_user', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_user_date_created'), 'contest_user', ['date_created'], unique=False)
    op.create_index(op.f('ix_contest_user_status'), 'contest_user', ['status'], unique=False)
    op.create_index(op.f('ix_contest_user_user_id'), 'contest_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_date_created'), 'message', ['date_created'], unique=False)
    op.create_index(op.f('ix_message_from_user_id'), 'message', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_message_is_read'), 'message', ['is_read'], unique=False)
    op.create_index(op.f('ix_message_to_user_id'), 'message', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_news_date_created'), 'news', ['date_created'], unique=False)
    op.create_index(op.f('ix_news_is_display'), 'news', ['is_display'], unique=False)
    op.create_index(op.f('ix_news_user_id'), 'news', ['user_id'], unique=False)
    op.alter_column('problem', 'memory_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('problem', 'time_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_problem_date_created'), 'problem', ['date_created'], unique=False)
    op.create_index(op.f('ix_problem_date_modified'), 'problem', ['date_modified'], unique=False)
    op.create_index(op.f('ix_problem_is_display'), 'problem', ['is_display'], unique=False)
    op.create_index(op.f('ix_problem_is_special_judge'), 'problem', ['is_special_judge'], unique=False)
    op.create_index(op.f('ix_solution_contest_id'), 'solution', ['contest_id'], unique=False)
    op.create_index(op.f('ix_solution_contest_user_id'), 'solution', ['contest_user_id'], unique=False)
    op.create_index(op.f('ix_solution_date_created'), 'solution', ['date_created'], unique=False)
    op.create_index(op.f('ix_solution_problem_id'), 'solution', ['problem_id'], unique=False)
    op.create_index(op.f('ix_solution_program_language'), 'solution', ['program_language'], unique=False)
    op.create_index(op.f('ix_solution_result'), 'solution', ['result'], unique=False)
    op.create_index(op.f('ix_solution_user_id'), 'solution', ['user_id'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.drop_constraint(u'user_nickname_key', 'user', type_='unique')
    op.alter_column('user_deleted', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_deleted', 'nickname',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_deleted', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user_deleted', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user_deleted', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_index(op.f('ix_user_deleted_date_created'), 'user_deleted', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_deleted_nickname'), 'user_deleted', ['nickname'], unique=True)
    op.drop_constraint(u'user_deleted_nickname_key', 'user_deleted', type_='unique')
    op.create_index(op.f('ix_user_favorites_problem_id'), 'user_favorites', ['problem_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_problem_id'), table_name='user_favorites')
    op.create_unique_constraint(u'user_deleted_nickname_key', 'user_deleted', ['nickname'])
    op.drop_index(op.f('ix_user_deleted_nickname'), table_name='user_deleted')
    op.drop_index(op.f('ix_user_deleted_date_created'), table_name='user_deleted')
    op.alter_column('user_deleted', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_deleted', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user_deleted', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_deleted', 'nickname',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_deleted', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_unique_constraint(u'user_nickname_key', 'user', ['nickname'])
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_index(op.f('ix_solution_user_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_result'), table_name='solution')
    op.drop_index(op.f('ix_solution_program_language'), table_name='solution')
    op.drop_index(op.f('ix_solution_problem_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_date_created'), table_name='solution')
    op.drop_index(op.f('ix_solution_contest_user_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_contest_id'), table_name='solution')
    op.drop_index(op.f('ix_problem_is_special_judge'), table_name='problem')
    op.drop_index(op.f('ix_problem_is_display'), table_name='problem')
    op.drop_index(op.f('ix_problem_date_modified'), table_name='problem')
    op.drop_index(op.f('ix_problem_date_created'), table_name='problem')
    op.alter_column('problem', 'time_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('problem', 'memory_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_news_user_id'), table_name='news')
    op.drop_index(op.f('ix_news_is_display'), table_name='news')
    op.drop_index(op.f('ix_news_date_created'), table_name='news')
    op.drop_index(op.f('ix_message_to_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_is_read'), table_name='message')
    op.drop_index(op.f('ix_message_from_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_date_created'), table_name='message')
    op.drop_index(op.f('ix_contest_user_user_id'), table_name='contest_user')
    op.drop_index(op.f('ix_contest_user_status'), table_name='contest_user')
    op.drop_index(op.f('ix_contest_user_date_created'), table_name='contest_user')
    op.drop_index(op.f('ix_contest_user_contest_id'), table_name='contest_user')
    op.drop_index(op.f('ix_contest_problem_problem_id'), table_name='contest_problem')
    op.drop_index(op.f('ix_contest_problem_ordinal'), table_name='contest_problem')
    op.drop_index(op.f('ix_contest_problem_date_created'), table_name='contest_problem')
    op.drop_index(op.f('ix_contest_problem_contest_id'), table_name='contest_problem')
    op.drop_index(op.f('ix_contest_user_id'), table_name='contest')
    op.drop_index(op.f('ix_contest_date_created'), table_name='contest')
    op.drop_index(op.f('ix_compile_info_date_created'), table_name='compile_info')
    op.drop_index(op.f('ix_compile_info_code_id'), table_name='compile_info')
    op.drop_index(op.f('ix_code_solution_id'), table_name='code')
    op.drop_index(op.f('ix_code_date_created'), table_name='code')
    ### end Alembic commands ###
