"""empty message

Revision ID: 2d4e9c6f8e09
Revises: 39f198b82f44
Create Date: 2015-03-15 22:48:04.692699

"""

# revision identifiers, used by Alembic.
revision = '2d4e9c6f8e09'
down_revision = '39f198b82f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_deleted',
    sa.Column('date_deleted', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('school', sa.String(length=256), nullable=True),
    sa.Column('program_language', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deleted_date_deleted'), 'user_deleted', ['date_deleted'], unique=False)
    op.create_index(op.f('ix_user_deleted_email'), 'user_deleted', ['email'], unique=False)
    op.create_index(op.f('ix_user_deleted_username'), 'user_deleted', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_username'), table_name='user_deleted')
    op.drop_index(op.f('ix_user_deleted_email'), table_name='user_deleted')
    op.drop_index(op.f('ix_user_deleted_date_deleted'), table_name='user_deleted')
    op.drop_table('user_deleted')
    ### end Alembic commands ###
