"""empty message

Revision ID: 366d5d12bb83
Revises: 4c38b5b7dfe5
Create Date: 2015-04-11 11:40:18.983694

"""

# revision identifiers, used by Alembic.
revision = '366d5d12bb83'
down_revision = '4c38b5b7dfe5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ENUM(u'deleted_by_user', u'deleted_by_admin', u'censored_automatically', name='deleted_reason').create(op.get_bind(), checkfirst=False)
    op.add_column('user_deleted', sa.Column('reason', sa.Enum(u'deleted_by_user', u'deleted_by_admin', u'censored_automatically', name='deleted_reason'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_deleted', 'reason')
    ENUM(name=u'deleted_reason').drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
