"""add is_read to message model

Revision ID: 3c11c7cfbd81
Revises: 4e51d69d2639
Create Date: 2015-03-22 09:37:22.798203

"""

# revision identifiers, used by Alembic.
revision = '3c11c7cfbd81'
down_revision = '4e51d69d2639'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    ### end Alembic commands ###
