"""empty message

Revision ID: 43680123b6d9
Revises: 277bfeb5755b
Create Date: 2015-03-29 13:30:02.730953

"""

# revision identifiers, used by Alembic.
revision = '43680123b6d9'
down_revision = '277bfeb5755b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ENUM(u'public', u'private', u'register', u'diy', name=u'contest_type_enum').create(op.get_bind(), checkfirst=False)
    ENUM(u'accept', u'waiting', u'reject', u'again', name=u'contest_user_status_enum').create(op.get_bind(), checkfirst=False)
    op.add_column('contest', sa.Column('date_end', sa.DateTime(), nullable=False))
    op.add_column('contest', sa.Column('date_end_register', sa.DateTime(), nullable=False))
    op.add_column('contest', sa.Column('date_start', sa.DateTime(), nullable=False))
    op.add_column('contest', sa.Column('date_start_register', sa.DateTime(), nullable=False))
    op.add_column('contest', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column('contest', sa.Column('is_hiden', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    op.add_column('contest', sa.Column('name', sa.Unicode(length=512), nullable=False))
    op.add_column('contest', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('contest', sa.Column('type', sa.Enum(u'public', u'private', u'register', u'diy', name='contest_type_enum'), server_default=u'public', nullable=False))
    op.add_column('contest', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('contest', 'title')
    op.add_column('contest_problem', sa.Column('name', sa.Unicode(length=512), nullable=True))
    op.add_column('contest_user', sa.Column('clazz', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('clazz1', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('clazz2', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('college', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('college1', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('college2', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('email1', sa.String(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('email2', sa.String(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('login_name', sa.String(length=256), nullable=False))
    op.add_column('contest_user', sa.Column('major', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('major1', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('major2', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('name', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('name1', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('name2', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('contest_user', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('phone1', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('phone2', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('reason', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('school', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('school1', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('school2', sa.Unicode(length=256), nullable=True))
    op.add_column('contest_user', sa.Column('seat_number', sa.Unicode(length=128), nullable=True))
    op.add_column('contest_user', sa.Column('status', sa.Enum(u'accept', u'waiting', u'reject', u'again', name=u'contest_user_status_enum'), server_default=u'waiting', nullable=False))
    op.add_column('contest_user', sa.Column('student_id', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('student_id1', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('student_id2', sa.String(length=32), nullable=True))
    op.add_column('contest_user', sa.Column('team_name', sa.Unicode(length=256), nullable=False))
    op.add_column('contest_user', sa.Column('user_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_user', 'user_id')
    op.drop_column('contest_user', 'team_name')
    op.drop_column('contest_user', 'student_id2')
    op.drop_column('contest_user', 'student_id1')
    op.drop_column('contest_user', 'student_id')
    op.drop_column('contest_user', 'status')
    op.drop_column('contest_user', 'seat_number')
    op.drop_column('contest_user', 'school2')
    op.drop_column('contest_user', 'school1')
    op.drop_column('contest_user', 'school')
    op.drop_column('contest_user', 'reason')
    op.drop_column('contest_user', 'phone2')
    op.drop_column('contest_user', 'phone1')
    op.drop_column('contest_user', 'phone')
    op.drop_column('contest_user', 'password_hash')
    op.drop_column('contest_user', 'name2')
    op.drop_column('contest_user', 'name1')
    op.drop_column('contest_user', 'name')
    op.drop_column('contest_user', 'major2')
    op.drop_column('contest_user', 'major1')
    op.drop_column('contest_user', 'major')
    op.drop_column('contest_user', 'login_name')
    op.drop_column('contest_user', 'email2')
    op.drop_column('contest_user', 'email1')
    op.drop_column('contest_user', 'email')
    op.drop_column('contest_user', 'college2')
    op.drop_column('contest_user', 'college1')
    op.drop_column('contest_user', 'college')
    op.drop_column('contest_user', 'clazz2')
    op.drop_column('contest_user', 'clazz1')
    op.drop_column('contest_user', 'clazz')
    op.drop_column('contest_problem', 'name')
    op.add_column('contest', sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('contest', 'user_id')
    op.drop_column('contest', 'type')
    op.drop_column('contest', 'password_hash')
    op.drop_column('contest', 'name')
    op.drop_column('contest', 'is_hiden')
    op.drop_column('contest', 'description')
    op.drop_column('contest', 'date_start_register')
    op.drop_column('contest', 'date_start')
    op.drop_column('contest', 'date_end_register')
    op.drop_column('contest', 'date_end')
    ENUM(name=u'contest_user_status_enum').drop(op.get_bind(), checkfirst=False)
    ENUM(name=u'contest_type_enum').drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
