"""empty message

Revision ID: 4e51d69d2639
Revises: 4e9d2ae177b0
Create Date: 2015-03-21 17:59:16.822576

"""

# revision identifiers, used by Alembic.
revision = '4e51d69d2639'
down_revision = '4e9d2ae177b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ENUM(u'male', u'female', name=u'user_gender').create(op.get_bind(), checkfirst=False)
    op.add_column('user', sa.Column('gender', sa.Enum(u'male', u'female', name='user_gender'), nullable=True))
    op.add_column('user_deleted', sa.Column('gender', sa.Enum(u'male', u'female', name='user_gender'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_deleted', 'gender')
    op.drop_column('user', 'gender')
    ENUM(name=u'user_gender').drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
