"""empty message

Revision ID: 4e9d2ae177b0
Revises: 2d4e9c6f8e09
Create Date: 2015-03-21 17:42:41.694189

"""

# revision identifiers, used by Alembic.
revision = '4e9d2ae177b0'
down_revision = '2d4e9c6f8e09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_date_created'), 'user_favorites', ['date_created'], unique=False)
    op.create_table('code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('take_time', sa.Integer(), nullable=False),
    sa.Column('take_memory', sa.Integer(), nullable=False),
    sa.Column('program_language', sa.String(length=64), nullable=False),
    sa.Column('compile_info_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compile_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'problem_title_key', 'problem', type_='unique')
    op.add_column(u'solution', sa.Column('code_id', sa.Integer(), nullable=False))
    op.drop_column(u'solution', 'take_time')
    op.drop_column(u'solution', 'program_language')
    op.drop_column(u'solution', 'take_memory')
    op.drop_column(u'solution', 'code_length')
    op.drop_index('ix_user_deleted_email', table_name='user_deleted')
    op.create_index(op.f('ix_user_deleted_email'), 'user_deleted', ['email'], unique=True)
    op.drop_index('ix_user_deleted_username', table_name='user_deleted')
    op.create_index(op.f('ix_user_deleted_username'), 'user_deleted', ['username'], unique=True)
    op.create_unique_constraint(None, 'user_deleted', ['nickname'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_deleted', type_='unique')
    op.drop_index(op.f('ix_user_deleted_username'), table_name='user_deleted')
    op.create_index('ix_user_deleted_username', 'user_deleted', ['username'], unique=False)
    op.drop_index(op.f('ix_user_deleted_email'), table_name='user_deleted')
    op.create_index('ix_user_deleted_email', 'user_deleted', ['email'], unique=False)
    op.add_column(u'solution', sa.Column('code_length', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'solution', sa.Column('take_memory', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'solution', sa.Column('program_language', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column(u'solution', sa.Column('take_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column(u'solution', 'code_id')
    op.create_unique_constraint(u'problem_title_key', 'problem', ['title'])
    op.drop_table('contest')
    op.drop_table('contest_problem')
    op.drop_table('message')
    op.drop_table('compile_info')
    op.drop_table('code')
    op.drop_index(op.f('ix_user_favorites_date_created'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_table('news')
    ### end Alembic commands ###
