"""add is_bulk_registration to user model

Revision ID: 512be27ebe8c
Revises: 2563b1147545
Create Date: 2015-04-27 13:53:33.618097

"""

# revision identifiers, used by Alembic.
revision = '512be27ebe8c'
down_revision = '2563b1147545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bulk_registration', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    op.add_column('user_deleted', sa.Column('is_bulk_registration', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_deleted', 'is_bulk_registration')
    op.drop_column('user', 'is_bulk_registration')
    ### end Alembic commands ###
