"""fix confirmed field

Revision ID: 1e3beb7a772
Revises: 3211fb10978c
Create Date: 2015-10-14 21:58:58.526782

"""

# revision identifiers, used by Alembic.
revision = '1e3beb7a772'
down_revision = '3211fb10978c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_deleted', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_deleted', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
