"""empty message

Revision ID: 277bfeb5755b
Revises: 4b9d1ee0914c
Create Date: 2015-03-26 20:23:57.471506

"""

# revision identifiers, used by Alembic.
revision = '277bfeb5755b'
down_revision = '4b9d1ee0914c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('solution_id', sa.Integer(), nullable=False))
    op.drop_column('code', 'take_time')
    op.drop_column('code', 'length')
    op.drop_column('code', 'program_language')
    op.drop_column('code', 'take_memory')
    op.drop_column('code', 'compile_info_id')
    op.add_column('compile_info', sa.Column('code_id', sa.Integer(), nullable=False))
    op.add_column('solution', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('solution', sa.Column('program_language', sa.String(length=64), nullable=False))
    op.add_column('solution', sa.Column('take_memory', sa.Integer(), nullable=False))
    op.add_column('solution', sa.Column('take_time', sa.Integer(), nullable=False))
    op.drop_column('solution', 'code_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('code_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('solution', 'take_time')
    op.drop_column('solution', 'take_memory')
    op.drop_column('solution', 'program_language')
    op.drop_column('solution', 'length')
    op.drop_column('compile_info', 'code_id')
    op.add_column('code', sa.Column('compile_info_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('code', sa.Column('take_memory', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('code', sa.Column('program_language', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('code', sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('code', sa.Column('take_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('code', 'solution_id')
    ### end Alembic commands ###
