"""empty message

Revision ID: 357ea12d3d1
Revises: 2c6077bbbaa7
Create Date: 2015-04-12 01:07:50.118028

"""

# revision identifiers, used by Alembic.
revision = '357ea12d3d1'
down_revision = '2c6077bbbaa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user_deleted', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_deleted', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'program_language',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
