"""empty message

Revision ID: 39f198b82f44
Revises: 4024c2eec24e
Create Date: 2015-03-14 19:50:42.298264

"""

# revision identifiers, used by Alembic.
revision = '39f198b82f44'
down_revision = '4024c2eec24e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('take_time', sa.Integer(), nullable=False),
    sa.Column('take_memory', sa.Integer(), nullable=False),
    sa.Column('code_length', sa.Integer(), nullable=False),
    sa.Column('program_language', sa.String(length=64), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_statistics',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('solutions_count', sa.Integer(), server_default=u'0', nullable=False),
    sa.Column('accepts_count', sa.Integer(), server_default=u'0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_statistics_accepts_count'), 'user_statistics', ['accepts_count'], unique=False)
    op.create_index(op.f('ix_user_statistics_solutions_count'), 'user_statistics', ['solutions_count'], unique=False)
    op.add_column(u'user', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column(u'user', sa.Column('nickname', sa.String(length=256), nullable=True))
    op.add_column(u'user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column(u'user', sa.Column('program_language', sa.String(length=64), nullable=True))
    op.add_column(u'user', sa.Column('school', sa.String(length=256), nullable=True))
    op.alter_column(u'user', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint(u'user_username_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['nickname'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(u'user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column(u'user', 'username',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column(u'user', 'school')
    op.drop_column(u'user', 'program_language')
    op.drop_column(u'user', 'password_hash')
    op.drop_column(u'user', 'nickname')
    op.drop_column(u'user', 'email')
    op.drop_index(op.f('ix_user_statistics_solutions_count'), table_name='user_statistics')
    op.drop_index(op.f('ix_user_statistics_accepts_count'), table_name='user_statistics')
    op.drop_table('user_statistics')
    op.drop_table('solution')
    ### end Alembic commands ###
