"""update user model

Revision ID: 3c8de56eeebc
Revises: 512be27ebe8c
Create Date: 2015-05-21 23:01:27.086464

"""

# revision identifiers, used by Alembic.
revision = '3c8de56eeebc'
down_revision = '512be27ebe8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('clazz', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('college', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('grade', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('major', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('qq', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user_deleted', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user_deleted', sa.Column('clazz', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('college', sa.String(length=256), nullable=True))
    op.add_column('user_deleted', sa.Column('grade', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('major', sa.String(length=256), nullable=True))
    op.add_column('user_deleted', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('qq', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_deleted', 'qq')
    op.drop_column('user_deleted', 'phone')
    op.drop_column('user_deleted', 'major')
    op.drop_column('user_deleted', 'grade')
    op.drop_column('user_deleted', 'college')
    op.drop_column('user_deleted', 'clazz')
    op.drop_column('user_deleted', 'avatar')
    op.drop_column('user_deleted', 'address')
    op.drop_column('user', 'qq')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'major')
    op.drop_column('user', 'grade')
    op.drop_column('user', 'college')
    op.drop_column('user', 'clazz')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'address')
    ### end Alembic commands ###
