"""empty message

Revision ID: 4dd00a9bd420
Revises: 43680123b6d9
Create Date: 2015-03-31 11:35:05.397005

"""

# revision identifiers, used by Alembic.
revision = '4dd00a9bd420'
down_revision = '43680123b6d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'date_end_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contest', 'date_start_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'date_start_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contest', 'date_end_register',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
