"""add role model

Revision ID: 532a3998fa9f
Revises: 582f01ebf33e
Create Date: 2015-04-12 23:39:50.255376

"""

# revision identifiers, used by Alembic.
revision = '532a3998fa9f'
down_revision = '582f01ebf33e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), server_default=sa.text(u'false'), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.add_column(u'user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column(u'user_deleted', sa.Column('role_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user_deleted', 'role_id')
    op.drop_column(u'user', 'role_id')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    ### end Alembic commands ###
