"""empty message

Revision ID: 582f01ebf33e
Revises: 357ea12d3d1
Create Date: 2015-04-12 10:27:06.490122

"""

# revision identifiers, used by Alembic.
revision = '582f01ebf33e'
down_revision = '357ea12d3d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('date_current_login', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user', sa.Column('date_last_login', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user_deleted', sa.Column('current_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('date_current_login', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_deleted', sa.Column('date_last_login', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_deleted', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user_deleted', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_deleted', 'login_count')
    op.drop_column('user_deleted', 'last_login_ip')
    op.drop_column('user_deleted', 'date_last_login')
    op.drop_column('user_deleted', 'date_current_login')
    op.drop_column('user_deleted', 'current_login_ip')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'date_last_login')
    op.drop_column('user', 'date_current_login')
    op.drop_column('user', 'current_login_ip')
    ### end Alembic commands ###
